name: Run Python Script Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # 매 10분마다 실행

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydrive2 pandas requests  # 필요한 패키지 설치

    - name: Run Python script
      run: python HW_08/upload_to_gdrive.py
      env:
        GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
