name: Run Python Script Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # 매 10분마다 실행

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f HW_08/requirements.txt ]; then pip install -r HW_08/requirements.txt; fi

    - name: Run Python script
      run: |
        python HW_08/get_data.py  # 상대 경로로 수정
      env:
        MY_GITHUB_TOKEN: ${{ secrets.SOLA_GITHUB_TOKEN }}

    - name: Commit and push changes
      run: |
        git config --global user.name "ffe4el"
        git add HW_08/weather_data/*  # 상대 경로로 수정
        git commit -m "Update Weather Data - $(TZ='Asia/Seoul' date +'%Y-%m-%d')"
        git push
